# Generated by Django 6.0.6 on 2026-06-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='banner_image',
        ),
    ]
