# Generated by Django 6.0.6 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
