<<<<<<<< HEAD:accounts/migrations/0002_remove_user_phone_user_phone_number.py
# Generated by Django 6.0.6 on 2026-06-19 05:45
========
# Generated by Django 6.0.6 on 2026-06-15 10:17
>>>>>>>> cb5f4140c3cc005de1dc419a90539e1b44ab8a8a:accounts/migrations/0003_user_username.py

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
<<<<<<<< HEAD:accounts/migrations/0002_remove_user_phone_user_phone_number.py
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
========
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
>>>>>>>> cb5f4140c3cc005de1dc419a90539e1b44ab8a8a:accounts/migrations/0003_user_username.py
        ),
    ]
